#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34011
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlataformaWeb.Dao
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PLATAFORMAWEB")]
	public partial class DiagramaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Insertaspnet_Membership(aspnet_Membership instance);
    partial void Updateaspnet_Membership(aspnet_Membership instance);
    partial void Deleteaspnet_Membership(aspnet_Membership instance);
    partial void InsertTB_Proyecto(TB_Proyecto instance);
    partial void UpdateTB_Proyecto(TB_Proyecto instance);
    partial void DeleteTB_Proyecto(TB_Proyecto instance);
    partial void InsertTB_Resultado(TB_Resultado instance);
    partial void UpdateTB_Resultado(TB_Resultado instance);
    partial void DeleteTB_Resultado(TB_Resultado instance);
    partial void InsertTB_Seleccion(TB_Seleccion instance);
    partial void UpdateTB_Seleccion(TB_Seleccion instance);
    partial void DeleteTB_Seleccion(TB_Seleccion instance);
    partial void InsertTB_Ficha(TB_Ficha instance);
    partial void UpdateTB_Ficha(TB_Ficha instance);
    partial void DeleteTB_Ficha(TB_Ficha instance);
    #endregion
		
		public DiagramaDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ApplicationServices"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DiagramaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DiagramaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DiagramaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DiagramaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<aspnet_Membership> aspnet_Membership
		{
			get
			{
				return this.GetTable<aspnet_Membership>();
			}
		}
		
		public System.Data.Linq.Table<TB_Proyecto> TB_Proyecto
		{
			get
			{
				return this.GetTable<TB_Proyecto>();
			}
		}
		
		public System.Data.Linq.Table<TB_Resultado> TB_Resultado
		{
			get
			{
				return this.GetTable<TB_Resultado>();
			}
		}
		
		public System.Data.Linq.Table<TB_Seleccion> TB_Seleccion
		{
			get
			{
				return this.GetTable<TB_Seleccion>();
			}
		}
		
		public System.Data.Linq.Table<TB_Ficha> TB_Ficha
		{
			get
			{
				return this.GetTable<TB_Ficha>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.aspnet_Membership")]
	public partial class aspnet_Membership : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ApplicationId;
		
		private System.Guid _UserId;
		
		private string _Password;
		
		private int _PasswordFormat;
		
		private string _PasswordSalt;
		
		private string _MobilePIN;
		
		private string _Email;
		
		private string _LoweredEmail;
		
		private string _PasswordQuestion;
		
		private string _PasswordAnswer;
		
		private bool _IsApproved;
		
		private bool _IsLockedOut;
		
		private System.DateTime _CreateDate;
		
		private System.DateTime _LastLoginDate;
		
		private System.DateTime _LastPasswordChangedDate;
		
		private System.DateTime _LastLockoutDate;
		
		private int _FailedPasswordAttemptCount;
		
		private System.DateTime _FailedPasswordAttemptWindowStart;
		
		private int _FailedPasswordAnswerAttemptCount;
		
		private System.DateTime _FailedPasswordAnswerAttemptWindowStart;
		
		private string _Comment;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnApplicationIdChanging(System.Guid value);
    partial void OnApplicationIdChanged();
    partial void OnUserIdChanging(System.Guid value);
    partial void OnUserIdChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnPasswordFormatChanging(int value);
    partial void OnPasswordFormatChanged();
    partial void OnPasswordSaltChanging(string value);
    partial void OnPasswordSaltChanged();
    partial void OnMobilePINChanging(string value);
    partial void OnMobilePINChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnLoweredEmailChanging(string value);
    partial void OnLoweredEmailChanged();
    partial void OnPasswordQuestionChanging(string value);
    partial void OnPasswordQuestionChanged();
    partial void OnPasswordAnswerChanging(string value);
    partial void OnPasswordAnswerChanged();
    partial void OnIsApprovedChanging(bool value);
    partial void OnIsApprovedChanged();
    partial void OnIsLockedOutChanging(bool value);
    partial void OnIsLockedOutChanged();
    partial void OnCreateDateChanging(System.DateTime value);
    partial void OnCreateDateChanged();
    partial void OnLastLoginDateChanging(System.DateTime value);
    partial void OnLastLoginDateChanged();
    partial void OnLastPasswordChangedDateChanging(System.DateTime value);
    partial void OnLastPasswordChangedDateChanged();
    partial void OnLastLockoutDateChanging(System.DateTime value);
    partial void OnLastLockoutDateChanged();
    partial void OnFailedPasswordAttemptCountChanging(int value);
    partial void OnFailedPasswordAttemptCountChanged();
    partial void OnFailedPasswordAttemptWindowStartChanging(System.DateTime value);
    partial void OnFailedPasswordAttemptWindowStartChanged();
    partial void OnFailedPasswordAnswerAttemptCountChanging(int value);
    partial void OnFailedPasswordAnswerAttemptCountChanged();
    partial void OnFailedPasswordAnswerAttemptWindowStartChanging(System.DateTime value);
    partial void OnFailedPasswordAnswerAttemptWindowStartChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    #endregion
		
		public aspnet_Membership()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicationId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ApplicationId
		{
			get
			{
				return this._ApplicationId;
			}
			set
			{
				if ((this._ApplicationId != value))
				{
					this.OnApplicationIdChanging(value);
					this.SendPropertyChanging();
					this._ApplicationId = value;
					this.SendPropertyChanged("ApplicationId");
					this.OnApplicationIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordFormat", DbType="Int NOT NULL")]
		public int PasswordFormat
		{
			get
			{
				return this._PasswordFormat;
			}
			set
			{
				if ((this._PasswordFormat != value))
				{
					this.OnPasswordFormatChanging(value);
					this.SendPropertyChanging();
					this._PasswordFormat = value;
					this.SendPropertyChanged("PasswordFormat");
					this.OnPasswordFormatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordSalt", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string PasswordSalt
		{
			get
			{
				return this._PasswordSalt;
			}
			set
			{
				if ((this._PasswordSalt != value))
				{
					this.OnPasswordSaltChanging(value);
					this.SendPropertyChanging();
					this._PasswordSalt = value;
					this.SendPropertyChanged("PasswordSalt");
					this.OnPasswordSaltChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobilePIN", DbType="NVarChar(16)")]
		public string MobilePIN
		{
			get
			{
				return this._MobilePIN;
			}
			set
			{
				if ((this._MobilePIN != value))
				{
					this.OnMobilePINChanging(value);
					this.SendPropertyChanging();
					this._MobilePIN = value;
					this.SendPropertyChanged("MobilePIN");
					this.OnMobilePINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(256)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoweredEmail", DbType="NVarChar(256)")]
		public string LoweredEmail
		{
			get
			{
				return this._LoweredEmail;
			}
			set
			{
				if ((this._LoweredEmail != value))
				{
					this.OnLoweredEmailChanging(value);
					this.SendPropertyChanging();
					this._LoweredEmail = value;
					this.SendPropertyChanged("LoweredEmail");
					this.OnLoweredEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordQuestion", DbType="NVarChar(256)")]
		public string PasswordQuestion
		{
			get
			{
				return this._PasswordQuestion;
			}
			set
			{
				if ((this._PasswordQuestion != value))
				{
					this.OnPasswordQuestionChanging(value);
					this.SendPropertyChanging();
					this._PasswordQuestion = value;
					this.SendPropertyChanged("PasswordQuestion");
					this.OnPasswordQuestionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordAnswer", DbType="NVarChar(128)")]
		public string PasswordAnswer
		{
			get
			{
				return this._PasswordAnswer;
			}
			set
			{
				if ((this._PasswordAnswer != value))
				{
					this.OnPasswordAnswerChanging(value);
					this.SendPropertyChanging();
					this._PasswordAnswer = value;
					this.SendPropertyChanged("PasswordAnswer");
					this.OnPasswordAnswerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsApproved", DbType="Bit NOT NULL")]
		public bool IsApproved
		{
			get
			{
				return this._IsApproved;
			}
			set
			{
				if ((this._IsApproved != value))
				{
					this.OnIsApprovedChanging(value);
					this.SendPropertyChanging();
					this._IsApproved = value;
					this.SendPropertyChanged("IsApproved");
					this.OnIsApprovedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsLockedOut", DbType="Bit NOT NULL")]
		public bool IsLockedOut
		{
			get
			{
				return this._IsLockedOut;
			}
			set
			{
				if ((this._IsLockedOut != value))
				{
					this.OnIsLockedOutChanging(value);
					this.SendPropertyChanging();
					this._IsLockedOut = value;
					this.SendPropertyChanged("IsLockedOut");
					this.OnIsLockedOutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastLoginDate", DbType="DateTime NOT NULL")]
		public System.DateTime LastLoginDate
		{
			get
			{
				return this._LastLoginDate;
			}
			set
			{
				if ((this._LastLoginDate != value))
				{
					this.OnLastLoginDateChanging(value);
					this.SendPropertyChanging();
					this._LastLoginDate = value;
					this.SendPropertyChanged("LastLoginDate");
					this.OnLastLoginDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastPasswordChangedDate", DbType="DateTime NOT NULL")]
		public System.DateTime LastPasswordChangedDate
		{
			get
			{
				return this._LastPasswordChangedDate;
			}
			set
			{
				if ((this._LastPasswordChangedDate != value))
				{
					this.OnLastPasswordChangedDateChanging(value);
					this.SendPropertyChanging();
					this._LastPasswordChangedDate = value;
					this.SendPropertyChanged("LastPasswordChangedDate");
					this.OnLastPasswordChangedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastLockoutDate", DbType="DateTime NOT NULL")]
		public System.DateTime LastLockoutDate
		{
			get
			{
				return this._LastLockoutDate;
			}
			set
			{
				if ((this._LastLockoutDate != value))
				{
					this.OnLastLockoutDateChanging(value);
					this.SendPropertyChanging();
					this._LastLockoutDate = value;
					this.SendPropertyChanged("LastLockoutDate");
					this.OnLastLockoutDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FailedPasswordAttemptCount", DbType="Int NOT NULL")]
		public int FailedPasswordAttemptCount
		{
			get
			{
				return this._FailedPasswordAttemptCount;
			}
			set
			{
				if ((this._FailedPasswordAttemptCount != value))
				{
					this.OnFailedPasswordAttemptCountChanging(value);
					this.SendPropertyChanging();
					this._FailedPasswordAttemptCount = value;
					this.SendPropertyChanged("FailedPasswordAttemptCount");
					this.OnFailedPasswordAttemptCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FailedPasswordAttemptWindowStart", DbType="DateTime NOT NULL")]
		public System.DateTime FailedPasswordAttemptWindowStart
		{
			get
			{
				return this._FailedPasswordAttemptWindowStart;
			}
			set
			{
				if ((this._FailedPasswordAttemptWindowStart != value))
				{
					this.OnFailedPasswordAttemptWindowStartChanging(value);
					this.SendPropertyChanging();
					this._FailedPasswordAttemptWindowStart = value;
					this.SendPropertyChanged("FailedPasswordAttemptWindowStart");
					this.OnFailedPasswordAttemptWindowStartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FailedPasswordAnswerAttemptCount", DbType="Int NOT NULL")]
		public int FailedPasswordAnswerAttemptCount
		{
			get
			{
				return this._FailedPasswordAnswerAttemptCount;
			}
			set
			{
				if ((this._FailedPasswordAnswerAttemptCount != value))
				{
					this.OnFailedPasswordAnswerAttemptCountChanging(value);
					this.SendPropertyChanging();
					this._FailedPasswordAnswerAttemptCount = value;
					this.SendPropertyChanged("FailedPasswordAnswerAttemptCount");
					this.OnFailedPasswordAnswerAttemptCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FailedPasswordAnswerAttemptWindowStart", DbType="DateTime NOT NULL")]
		public System.DateTime FailedPasswordAnswerAttemptWindowStart
		{
			get
			{
				return this._FailedPasswordAnswerAttemptWindowStart;
			}
			set
			{
				if ((this._FailedPasswordAnswerAttemptWindowStart != value))
				{
					this.OnFailedPasswordAnswerAttemptWindowStartChanging(value);
					this.SendPropertyChanging();
					this._FailedPasswordAnswerAttemptWindowStart = value;
					this.SendPropertyChanged("FailedPasswordAnswerAttemptWindowStart");
					this.OnFailedPasswordAnswerAttemptWindowStartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_Proyecto")]
	public partial class TB_Proyecto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _noProyecto;
		
		private string _deProyecto;
		
		private int _tiProyecto;
		
		private int _stProyecto;
		
		private int _TB_Proyecto_ID;
		
		private int _TB_Ficha_ID;
		
		private int _TB_Seleccion_ID;
		
		private EntityRef<TB_Seleccion> _TB_Seleccion;
		
		private EntityRef<TB_Ficha> _TB_Ficha;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnoProyectoChanging(string value);
    partial void OnnoProyectoChanged();
    partial void OndeProyectoChanging(string value);
    partial void OndeProyectoChanged();
    partial void OntiProyectoChanging(int value);
    partial void OntiProyectoChanged();
    partial void OnstProyectoChanging(int value);
    partial void OnstProyectoChanged();
    partial void OnTB_Proyecto_IDChanging(int value);
    partial void OnTB_Proyecto_IDChanged();
    partial void OnTB_Ficha_IDChanging(int value);
    partial void OnTB_Ficha_IDChanged();
    partial void OnTB_Seleccion_IDChanging(int value);
    partial void OnTB_Seleccion_IDChanged();
    #endregion
		
		public TB_Proyecto()
		{
			this._TB_Seleccion = default(EntityRef<TB_Seleccion>);
			this._TB_Ficha = default(EntityRef<TB_Ficha>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noProyecto", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string noProyecto
		{
			get
			{
				return this._noProyecto;
			}
			set
			{
				if ((this._noProyecto != value))
				{
					this.OnnoProyectoChanging(value);
					this.SendPropertyChanging();
					this._noProyecto = value;
					this.SendPropertyChanged("noProyecto");
					this.OnnoProyectoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deProyecto", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string deProyecto
		{
			get
			{
				return this._deProyecto;
			}
			set
			{
				if ((this._deProyecto != value))
				{
					this.OndeProyectoChanging(value);
					this.SendPropertyChanging();
					this._deProyecto = value;
					this.SendPropertyChanged("deProyecto");
					this.OndeProyectoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tiProyecto", DbType="Int NOT NULL")]
		public int tiProyecto
		{
			get
			{
				return this._tiProyecto;
			}
			set
			{
				if ((this._tiProyecto != value))
				{
					this.OntiProyectoChanging(value);
					this.SendPropertyChanging();
					this._tiProyecto = value;
					this.SendPropertyChanged("tiProyecto");
					this.OntiProyectoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stProyecto", DbType="Int NOT NULL")]
		public int stProyecto
		{
			get
			{
				return this._stProyecto;
			}
			set
			{
				if ((this._stProyecto != value))
				{
					this.OnstProyectoChanging(value);
					this.SendPropertyChanging();
					this._stProyecto = value;
					this.SendPropertyChanged("stProyecto");
					this.OnstProyectoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TB_Proyecto_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TB_Proyecto_ID
		{
			get
			{
				return this._TB_Proyecto_ID;
			}
			set
			{
				if ((this._TB_Proyecto_ID != value))
				{
					this.OnTB_Proyecto_IDChanging(value);
					this.SendPropertyChanging();
					this._TB_Proyecto_ID = value;
					this.SendPropertyChanged("TB_Proyecto_ID");
					this.OnTB_Proyecto_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TB_Ficha_ID", DbType="Int NOT NULL")]
		public int TB_Ficha_ID
		{
			get
			{
				return this._TB_Ficha_ID;
			}
			set
			{
				if ((this._TB_Ficha_ID != value))
				{
					if (this._TB_Ficha.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTB_Ficha_IDChanging(value);
					this.SendPropertyChanging();
					this._TB_Ficha_ID = value;
					this.SendPropertyChanged("TB_Ficha_ID");
					this.OnTB_Ficha_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TB_Seleccion_ID", DbType="Int NOT NULL")]
		public int TB_Seleccion_ID
		{
			get
			{
				return this._TB_Seleccion_ID;
			}
			set
			{
				if ((this._TB_Seleccion_ID != value))
				{
					if (this._TB_Seleccion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTB_Seleccion_IDChanging(value);
					this.SendPropertyChanging();
					this._TB_Seleccion_ID = value;
					this.SendPropertyChanged("TB_Seleccion_ID");
					this.OnTB_Seleccion_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_Seleccion_TB_Proyecto", Storage="_TB_Seleccion", ThisKey="TB_Seleccion_ID", OtherKey="TB_Seleccion_ID", IsForeignKey=true)]
		public TB_Seleccion TB_Seleccion
		{
			get
			{
				return this._TB_Seleccion.Entity;
			}
			set
			{
				TB_Seleccion previousValue = this._TB_Seleccion.Entity;
				if (((previousValue != value) 
							|| (this._TB_Seleccion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_Seleccion.Entity = null;
						previousValue.TB_Proyecto.Remove(this);
					}
					this._TB_Seleccion.Entity = value;
					if ((value != null))
					{
						value.TB_Proyecto.Add(this);
						this._TB_Seleccion_ID = value.TB_Seleccion_ID;
					}
					else
					{
						this._TB_Seleccion_ID = default(int);
					}
					this.SendPropertyChanged("TB_Seleccion");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_Ficha_TB_Proyecto", Storage="_TB_Ficha", ThisKey="TB_Ficha_ID", OtherKey="TB_Ficha_ID", IsForeignKey=true)]
		public TB_Ficha TB_Ficha
		{
			get
			{
				return this._TB_Ficha.Entity;
			}
			set
			{
				TB_Ficha previousValue = this._TB_Ficha.Entity;
				if (((previousValue != value) 
							|| (this._TB_Ficha.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_Ficha.Entity = null;
						previousValue.TB_Proyecto.Remove(this);
					}
					this._TB_Ficha.Entity = value;
					if ((value != null))
					{
						value.TB_Proyecto.Add(this);
						this._TB_Ficha_ID = value.TB_Ficha_ID;
					}
					else
					{
						this._TB_Ficha_ID = default(int);
					}
					this.SendPropertyChanged("TB_Ficha");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_Resultado")]
	public partial class TB_Resultado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _noResultado;
		
		private string _deResultado;
		
		private int _tiResultado;
		
		private int _stResultado;
		
		private int _TB_Resultado_ID;
		
		private int _TB_Seleccion_ID;
		
		private EntityRef<TB_Seleccion> _TB_Seleccion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnoResultadoChanging(string value);
    partial void OnnoResultadoChanged();
    partial void OndeResultadoChanging(string value);
    partial void OndeResultadoChanged();
    partial void OntiResultadoChanging(int value);
    partial void OntiResultadoChanged();
    partial void OnstResultadoChanging(int value);
    partial void OnstResultadoChanged();
    partial void OnTB_Resultado_IDChanging(int value);
    partial void OnTB_Resultado_IDChanged();
    partial void OnTB_Seleccion_IDChanging(int value);
    partial void OnTB_Seleccion_IDChanged();
    #endregion
		
		public TB_Resultado()
		{
			this._TB_Seleccion = default(EntityRef<TB_Seleccion>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noResultado", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string noResultado
		{
			get
			{
				return this._noResultado;
			}
			set
			{
				if ((this._noResultado != value))
				{
					this.OnnoResultadoChanging(value);
					this.SendPropertyChanging();
					this._noResultado = value;
					this.SendPropertyChanged("noResultado");
					this.OnnoResultadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deResultado", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string deResultado
		{
			get
			{
				return this._deResultado;
			}
			set
			{
				if ((this._deResultado != value))
				{
					this.OndeResultadoChanging(value);
					this.SendPropertyChanging();
					this._deResultado = value;
					this.SendPropertyChanged("deResultado");
					this.OndeResultadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tiResultado", DbType="Int NOT NULL")]
		public int tiResultado
		{
			get
			{
				return this._tiResultado;
			}
			set
			{
				if ((this._tiResultado != value))
				{
					this.OntiResultadoChanging(value);
					this.SendPropertyChanging();
					this._tiResultado = value;
					this.SendPropertyChanged("tiResultado");
					this.OntiResultadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stResultado", DbType="Int NOT NULL")]
		public int stResultado
		{
			get
			{
				return this._stResultado;
			}
			set
			{
				if ((this._stResultado != value))
				{
					this.OnstResultadoChanging(value);
					this.SendPropertyChanging();
					this._stResultado = value;
					this.SendPropertyChanged("stResultado");
					this.OnstResultadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TB_Resultado_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TB_Resultado_ID
		{
			get
			{
				return this._TB_Resultado_ID;
			}
			set
			{
				if ((this._TB_Resultado_ID != value))
				{
					this.OnTB_Resultado_IDChanging(value);
					this.SendPropertyChanging();
					this._TB_Resultado_ID = value;
					this.SendPropertyChanged("TB_Resultado_ID");
					this.OnTB_Resultado_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TB_Seleccion_ID", DbType="Int NOT NULL")]
		public int TB_Seleccion_ID
		{
			get
			{
				return this._TB_Seleccion_ID;
			}
			set
			{
				if ((this._TB_Seleccion_ID != value))
				{
					if (this._TB_Seleccion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTB_Seleccion_IDChanging(value);
					this.SendPropertyChanging();
					this._TB_Seleccion_ID = value;
					this.SendPropertyChanged("TB_Seleccion_ID");
					this.OnTB_Seleccion_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_Seleccion_TB_Resultado", Storage="_TB_Seleccion", ThisKey="TB_Seleccion_ID", OtherKey="TB_Seleccion_ID", IsForeignKey=true)]
		public TB_Seleccion TB_Seleccion
		{
			get
			{
				return this._TB_Seleccion.Entity;
			}
			set
			{
				TB_Seleccion previousValue = this._TB_Seleccion.Entity;
				if (((previousValue != value) 
							|| (this._TB_Seleccion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_Seleccion.Entity = null;
						previousValue.TB_Resultado.Remove(this);
					}
					this._TB_Seleccion.Entity = value;
					if ((value != null))
					{
						value.TB_Resultado.Add(this);
						this._TB_Seleccion_ID = value.TB_Seleccion_ID;
					}
					else
					{
						this._TB_Seleccion_ID = default(int);
					}
					this.SendPropertyChanged("TB_Seleccion");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_Seleccion")]
	public partial class TB_Seleccion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _noSeleccion;
		
		private string _deSeleccion;
		
		private int _tiSeleccion;
		
		private int _stSeleccion;
		
		private int _TB_Seleccion_ID;
		
		private EntitySet<TB_Proyecto> _TB_Proyecto;
		
		private EntitySet<TB_Resultado> _TB_Resultado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnoSeleccionChanging(string value);
    partial void OnnoSeleccionChanged();
    partial void OndeSeleccionChanging(string value);
    partial void OndeSeleccionChanged();
    partial void OntiSeleccionChanging(int value);
    partial void OntiSeleccionChanged();
    partial void OnstSeleccionChanging(int value);
    partial void OnstSeleccionChanged();
    partial void OnTB_Seleccion_IDChanging(int value);
    partial void OnTB_Seleccion_IDChanged();
    #endregion
		
		public TB_Seleccion()
		{
			this._TB_Proyecto = new EntitySet<TB_Proyecto>(new Action<TB_Proyecto>(this.attach_TB_Proyecto), new Action<TB_Proyecto>(this.detach_TB_Proyecto));
			this._TB_Resultado = new EntitySet<TB_Resultado>(new Action<TB_Resultado>(this.attach_TB_Resultado), new Action<TB_Resultado>(this.detach_TB_Resultado));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noSeleccion", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string noSeleccion
		{
			get
			{
				return this._noSeleccion;
			}
			set
			{
				if ((this._noSeleccion != value))
				{
					this.OnnoSeleccionChanging(value);
					this.SendPropertyChanging();
					this._noSeleccion = value;
					this.SendPropertyChanged("noSeleccion");
					this.OnnoSeleccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deSeleccion", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string deSeleccion
		{
			get
			{
				return this._deSeleccion;
			}
			set
			{
				if ((this._deSeleccion != value))
				{
					this.OndeSeleccionChanging(value);
					this.SendPropertyChanging();
					this._deSeleccion = value;
					this.SendPropertyChanged("deSeleccion");
					this.OndeSeleccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tiSeleccion", DbType="Int NOT NULL")]
		public int tiSeleccion
		{
			get
			{
				return this._tiSeleccion;
			}
			set
			{
				if ((this._tiSeleccion != value))
				{
					this.OntiSeleccionChanging(value);
					this.SendPropertyChanging();
					this._tiSeleccion = value;
					this.SendPropertyChanged("tiSeleccion");
					this.OntiSeleccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stSeleccion", DbType="Int NOT NULL")]
		public int stSeleccion
		{
			get
			{
				return this._stSeleccion;
			}
			set
			{
				if ((this._stSeleccion != value))
				{
					this.OnstSeleccionChanging(value);
					this.SendPropertyChanging();
					this._stSeleccion = value;
					this.SendPropertyChanged("stSeleccion");
					this.OnstSeleccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TB_Seleccion_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TB_Seleccion_ID
		{
			get
			{
				return this._TB_Seleccion_ID;
			}
			set
			{
				if ((this._TB_Seleccion_ID != value))
				{
					this.OnTB_Seleccion_IDChanging(value);
					this.SendPropertyChanging();
					this._TB_Seleccion_ID = value;
					this.SendPropertyChanged("TB_Seleccion_ID");
					this.OnTB_Seleccion_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_Seleccion_TB_Proyecto", Storage="_TB_Proyecto", ThisKey="TB_Seleccion_ID", OtherKey="TB_Seleccion_ID")]
		public EntitySet<TB_Proyecto> TB_Proyecto
		{
			get
			{
				return this._TB_Proyecto;
			}
			set
			{
				this._TB_Proyecto.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_Seleccion_TB_Resultado", Storage="_TB_Resultado", ThisKey="TB_Seleccion_ID", OtherKey="TB_Seleccion_ID")]
		public EntitySet<TB_Resultado> TB_Resultado
		{
			get
			{
				return this._TB_Resultado;
			}
			set
			{
				this._TB_Resultado.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TB_Proyecto(TB_Proyecto entity)
		{
			this.SendPropertyChanging();
			entity.TB_Seleccion = this;
		}
		
		private void detach_TB_Proyecto(TB_Proyecto entity)
		{
			this.SendPropertyChanging();
			entity.TB_Seleccion = null;
		}
		
		private void attach_TB_Resultado(TB_Resultado entity)
		{
			this.SendPropertyChanging();
			entity.TB_Seleccion = this;
		}
		
		private void detach_TB_Resultado(TB_Resultado entity)
		{
			this.SendPropertyChanging();
			entity.TB_Seleccion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_Ficha")]
	public partial class TB_Ficha : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _noFicha;
		
		private string _deFicha;
		
		private int _tiFicha;
		
		private int _stFicha;
		
		private int _TB_Ficha_ID;
		
		private EntitySet<TB_Proyecto> _TB_Proyecto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnoFichaChanging(string value);
    partial void OnnoFichaChanged();
    partial void OndeFichaChanging(string value);
    partial void OndeFichaChanged();
    partial void OntiFichaChanging(int value);
    partial void OntiFichaChanged();
    partial void OnstFichaChanging(int value);
    partial void OnstFichaChanged();
    partial void OnTB_Ficha_IDChanging(int value);
    partial void OnTB_Ficha_IDChanged();
    #endregion
		
		public TB_Ficha()
		{
			this._TB_Proyecto = new EntitySet<TB_Proyecto>(new Action<TB_Proyecto>(this.attach_TB_Proyecto), new Action<TB_Proyecto>(this.detach_TB_Proyecto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noFicha", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string noFicha
		{
			get
			{
				return this._noFicha;
			}
			set
			{
				if ((this._noFicha != value))
				{
					this.OnnoFichaChanging(value);
					this.SendPropertyChanging();
					this._noFicha = value;
					this.SendPropertyChanged("noFicha");
					this.OnnoFichaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deFicha", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string deFicha
		{
			get
			{
				return this._deFicha;
			}
			set
			{
				if ((this._deFicha != value))
				{
					this.OndeFichaChanging(value);
					this.SendPropertyChanging();
					this._deFicha = value;
					this.SendPropertyChanged("deFicha");
					this.OndeFichaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tiFicha", DbType="Int NOT NULL")]
		public int tiFicha
		{
			get
			{
				return this._tiFicha;
			}
			set
			{
				if ((this._tiFicha != value))
				{
					this.OntiFichaChanging(value);
					this.SendPropertyChanging();
					this._tiFicha = value;
					this.SendPropertyChanged("tiFicha");
					this.OntiFichaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stFicha", DbType="Int NOT NULL")]
		public int stFicha
		{
			get
			{
				return this._stFicha;
			}
			set
			{
				if ((this._stFicha != value))
				{
					this.OnstFichaChanging(value);
					this.SendPropertyChanging();
					this._stFicha = value;
					this.SendPropertyChanged("stFicha");
					this.OnstFichaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TB_Ficha_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TB_Ficha_ID
		{
			get
			{
				return this._TB_Ficha_ID;
			}
			set
			{
				if ((this._TB_Ficha_ID != value))
				{
					this.OnTB_Ficha_IDChanging(value);
					this.SendPropertyChanging();
					this._TB_Ficha_ID = value;
					this.SendPropertyChanged("TB_Ficha_ID");
					this.OnTB_Ficha_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_Ficha_TB_Proyecto", Storage="_TB_Proyecto", ThisKey="TB_Ficha_ID", OtherKey="TB_Ficha_ID")]
		public EntitySet<TB_Proyecto> TB_Proyecto
		{
			get
			{
				return this._TB_Proyecto;
			}
			set
			{
				this._TB_Proyecto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TB_Proyecto(TB_Proyecto entity)
		{
			this.SendPropertyChanging();
			entity.TB_Ficha = this;
		}
		
		private void detach_TB_Proyecto(TB_Proyecto entity)
		{
			this.SendPropertyChanging();
			entity.TB_Ficha = null;
		}
	}
}
#pragma warning restore 1591
