<?xml version="1.0" encoding="utf-8"?><Database Name="PLATAFORMAWEB" Class="DiagramaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=ASUS\SQLEXPRESS;Initial Catalog=PLATAFORMAWEB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ApplicationServices" Provider="System.Data.SqlClient" />
  <Table Name="dbo.aspnet_Membership" Member="aspnet_Membership">
    <Type Name="aspnet_Membership">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordFormat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PasswordSalt" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="MobilePIN" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="LoweredEmail" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PasswordQuestion" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PasswordAnswer" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="IsApproved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsLockedOut" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastPasswordChangedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLockoutDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAttemptCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAttemptWindowStart" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAnswerAttemptCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAnswerAttemptWindowStart" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Comment" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.TB_Proyecto" Member="TB_Proyecto">
    <Type Name="TB_Proyecto">
      <Column Name="noProyecto" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="deProyecto" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="tiProyecto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="stProyecto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TB_Proyecto_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TB_Ficha_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TB_Seleccion_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="TB_Seleccion_TB_Proyecto" Member="TB_Seleccion" ThisKey="TB_Seleccion_ID" OtherKey="TB_Seleccion_ID" Type="TB_Seleccion" IsForeignKey="true" />
      <Association Name="TB_Ficha_TB_Proyecto" Member="TB_Ficha" ThisKey="TB_Ficha_ID" OtherKey="TB_Ficha_ID" Type="TB_Ficha" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TB_Resultado" Member="TB_Resultado">
    <Type Name="TB_Resultado">
      <Column Name="noResultado" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="deResultado" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="tiResultado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="stResultado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TB_Resultado_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TB_Seleccion_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="TB_Seleccion_TB_Resultado" Member="TB_Seleccion" ThisKey="TB_Seleccion_ID" OtherKey="TB_Seleccion_ID" Type="TB_Seleccion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TB_Seleccion" Member="TB_Seleccion">
    <Type Name="TB_Seleccion">
      <Column Name="noSeleccion" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="deSeleccion" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="tiSeleccion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="stSeleccion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TB_Seleccion_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="TB_Seleccion_TB_Proyecto" Member="TB_Proyecto" ThisKey="TB_Seleccion_ID" OtherKey="TB_Seleccion_ID" Type="TB_Proyecto" />
      <Association Name="TB_Seleccion_TB_Resultado" Member="TB_Resultado" ThisKey="TB_Seleccion_ID" OtherKey="TB_Seleccion_ID" Type="TB_Resultado" />
    </Type>
  </Table>
  <Table Name="dbo.TB_Ficha" Member="TB_Ficha">
    <Type Name="TB_Ficha">
      <Column Name="noFicha" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="deFicha" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="tiFicha" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="stFicha" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TB_Ficha_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="TB_Ficha_TB_Proyecto" Member="TB_Proyecto" ThisKey="TB_Ficha_ID" OtherKey="TB_Ficha_ID" Type="TB_Proyecto" />
    </Type>
  </Table>
</Database>